DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;


CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
EMPLOYEEID NUMERIC PRIMARY KEY NOT NULL,
AGE NUMERIC,
CITY VARCHAR(20),
EMPLOYEESTART VARCHAR(20) NOT NULL,
EMPLOYEEFINISH VARCHAR(20) NOT NULL,
/*ATTRIBUTE VARCHAR(10) CHECK(ATTRIBUTE IN('EMPLOYEE','MANAGER')),*/
MANAGER NUMERIC REFERENCES EMPLOYEE(EMPLOYEEID),
DEPARTMENT NUMERIC
)   
CREATE TABLE PROJECT(
NAME VARCHAR(50),
PROJECTID NUMERIC PRIMARY KEY NOT NULL, 
EMPLOYEE NUMERIC REFERENCES EMPLOYEE(EMPLOYEEID),
PROJECTSTART VARCHAR(20) NOT NULL,
PROJECTFINISH VARCHAR(20) NOT NULL,
)
SELECT 

SELECT COUNT(P.PROJECTID)
FROM PROJECT P 